# Generated by Django 6.0.3 on 2026-03-15 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['full_name', 'employee_id'],
                'indexes': [models.Index(fields=['employee_id'], name='idx_employee_employeeid'), models.Index(fields=['email'], name='idx_employee_email')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee_id',), name='uniq_active_employee_employee_id'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='uniq_active_employee_email')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='app.employee')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='idx_attendance_employee_date'), models.Index(fields=['date'], name='idx_attendance_date')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_attendance_employee_date')],
            },
        ),
    ]
